### ISSUE TITLE
Despliegue de recetas

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [helio-ecosystem/helio-frontend#1]
Al desplegar las recetas con docker, el servicio del puerto 4567 no se encuentra en la misma red que el front end. Además al desplegar la receta de playground simple se despliega realmente la del playground con opciones avanzadas

**Comment by EmilioCrespoPeran** [comment]
Hecho! Bug encontrado en el fichero de despliegue que no contenía los argumentos del profile de playground.
