### ISSUE TITLE
Formato del texto de tutorials

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [helio-ecosystem/helio-frontend#15]
el nombre de los tutorials se modifica poniendo cada letra del comienzo de la palabra en mayusculas, por ejemplo `Generating and linking rdf about people and places` aparece como

![Captura de pantalla 2022-10-03 a las 11 11 54](https://user-images.githubusercontent.com/4105186/193541730-9413b365-1ae5-4798-b4e1-81f95a2aabaa.png)

¿Se podria cambiar para que se quede igual que el nombre del fichero?

**Comment by EmilioCrespoPeran** [comment]
Claro! lo modifico
