### ISSUE TITLE
Descripciones de los tutoriales en formato markdown

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [helio-ecosystem/helio-frontend#18]
Sería mucho trabajo hacer que las descripciones de los tour fueran markdown interpretable?

**Comment by EmilioCrespoPeran** [comment]
He visto una libreria en la que recogeria la descripcion y generaria el markdown resuelto, no la he probado pero no tiene mala pinta: https://github.com/danestves/markdown-to-text

Sin embargo, he intentado grabar un tutorial con la descripcion de un markdown y parece que tengo problemas a la hora de escribirlo en un json, podrías pasarme un ejemplo del tutorial?

Adjunto los errores que he probado, porque parece un problema de codificacion con el caracter "#"

![image](https://user-images.githubusercontent.com/38924290/197013894-2f572fc3-6031-4a35-bf1d-8e05bb7febda.png)

![image](https://user-images.githubusercontent.com/38924290/197013826-5e4e717f-6a60-4fc9-8aea-665af4b89157.png)

![image](https://user-images.githubusercontent.com/38924290/197013762-bcc71c24-718c-4ca5-b753-bf921bfd19cf.png)

**Comment by EmilioCrespoPeran** [comment]
Si te da problemas tambien, se me ocurre que quiza la descripcion sea una url de un fichero markdown y desde la api que tenemos de github rest, lo formatee. Si estos ficheros markdown estan en la misma raiz que el tutorial, podria meterles un filtro para los archivos ".md" y asi que no haya ningun problema.

**Comment by AndreaCimminoArriaga** [comment]
Yo creo que el error es por el salto de linea, lo que también nos pasa al meter las descipciones que no podemos separar en parrafos. Lo del fichero a parte me parece buena idea, se podria llamar igual que el fichero con los mappings pero con la extension .md.

La solución que veas que es más rápida y fácil de implementar.  Por cierto, hoy voy a mirar todo lo que me has mandado, espero contestarte lo antes posible ;)

**Comment by EmilioCrespoPeran** [comment]
He resuelto el problema, no es necesario crear otro fichero aparte con la descripción en formato markdown, con ponerlo en el json nos vale.

La librería en cuestión es esta: https://github.com/showdownjs/showdown

Lo único, es que hay que poner el markdown en una sola línea en los ficheros json, que eso era el motivo por el que me fallaba la validación del json. Habría que sustituir los saltos de línea por el texto "\n" y aquellos textos que tengan tabulación, por "\t" que los interpreta perfectamente.

Te muestro un ejemplo del tutorial en mi repositorio y el resultado:

```json
{
    "description": "\n## Seccion 1\n\t\t\t\tEjemplo de la seccion\n```java\nSystem.out.println(\"Hola mundo\");\n```\n## Seccion 2\n* item 1\n* item 2",
    "user_template": "Helllll wo",
    "solution_template": "Hello world!",
    "expected_result": "Hello world!"
}
```

![image](https://user-images.githubusercontent.com/38924290/197339907-a7fcac8f-ddc1-4073-a083-d6127cf98649.png)



Y otro con mas texto que viene del tutorial, lo encapsule todo en el description del json pero no me funciono. No se si es debido al limite del fichero que puede leer (ese markdown es enorme), pero para los tutoriales es muchisimo mas que suficiente.
Este markdown de ejemplo lo saqué de http://demo.showdownjs.com/ por si quieres echarle un vistazo.


```json
{
    "description": "![Showdown][sd-logo]\n\nShowdown is a Javascript Markdown to HTML converter, based on the original works by John Gruber. It can be used client side (in the browser) or server side (with Node or io).\n# Installation\n## Download tarball\nYou can download the latest release tarball directly from [releases][releases]\n## Bower\nbower install showdown\n## npm (server-side)\nnpm install showdown\n## CDN\nYou can also use one of several CDNs available:\n* rawgit CDN\nhttps://cdn.rawgit.com/showdownjs/showdown/<version tag>/dist/showdown.min.js\n cdnjs\nhttps://cdnjs.cloudflare.com/ajax/libs/showdown/<version tag>/showdown.min.js\n[sd-logo]: https://raw.githubusercontent.com/showdownjs/logo/master/dist/logo.readme.png\n[releases]: https://github.com/showdownjs/showdown/releases\n[atx]: http://www.aaronsw.com/2002/atx/intro\n[setext]: https://en.wikipedia.org/wiki/Setext\n---------\n",
    "user_template": "Helllll wo",
    "solution_template": "Hello world!",
    "expected_result": "Hello world!"
}
```


![image](https://user-images.githubusercontent.com/38924290/197339696-7ceb77f1-cb54-4ce7-9420-7dac1dc6a72f.png)
