### ISSUE TITLE
Componente duplicado al obtener los datos de la configuracion para PLAYGROUND

### ISSUE THREAD

**Issue by EmilioCrespoPeran** [helio-ecosystem/helio-frontend#20]
Se ha detectado que existe un problema al diferenciar los componentes ya instalados en el sistema.

![image](https://user-images.githubusercontent.com/38924290/198369001-9998cafc-e263-4c6e-9488-813e167503a1.png)

**Comment by EmilioCrespoPeran** [comment]
@AndreaCimminoArriaga por defecto Helio-Rest tiene unos componentes instalados pero al borrar uno "principal" (los que adjunto en la imagen), todos los componentes que ya tuviese instalados se eliminan.

Los pasos para reproducirlo son:
1. Agregar nuevos componentes.
2. Hacer petición para obtener la lista de componentes.
3. Eliminar un componente propio de Helio-Rest.

Con esos pasos, se resetean los componentes por defecto que hubiera.

![image](https://user-images.githubusercontent.com/38924290/198369726-e3f48ce7-b821-41ec-be56-96b467d55f95.png)

**Comment by AndreaCimminoArriaga** [comment]
Esto está ya arreglado, se usa el nombre de la clase (clazz) como id del componente. Si se desea instalar un componente que encapsula la misma clase (coinciden en paquete y nombre) este no se deja añadir. Para ello habría primero que borrar la version anterior.
