### ISSUE TITLE
Add field BUILDER in the mapping submission

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [helio-ecosystem/helio-frontend#5]

**Comment by AndreaCimminoArriaga** [comment]
Buenas, he desplegado el servicio para probar todo en https://helio-playground.linkeddata.es/playground, veo que tenemos dos problemas. Uno es que no se encuentra el servicio de helio rest (pero esto es por un tema de puertos que estoy resolviendo ya). El otro es que en la seccion de https://helio-playground.linkeddata.es/playground no aparece el campo para escoger el builder :(. Podríamos añadirlo para poder probar mappings con distintos builders ? (creo que esta feature ya estaba implementada, recuerdo haberla visto, no se si se ha perdido al actualizar la version)

**Comment by EmilioCrespoPeran** [comment]
Si, se me habia olvidado agregarlo ahi tambien
