### ISSUE TITLE
Add delete button to the components installed

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [helio-ecosystem/helio-frontend#6]

**Comment by EmilioCrespoPeran** [comment]
Se ha agregado la funcionalidad de eliminar un componente que no sea nativo de Helio-Rest, que son aquellos componentes que se agregan mediante el formulario.

![image](https://user-images.githubusercontent.com/38924290/190872360-7d72e4ab-c5ba-41aa-9ef0-6a59d290ad68.png)
